name: Azure Static Web Apps - CRA

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install
        run: npm ci --no-audit --no-fund

      - name: Build (CRA)
        env:
          CI: "false"
        run: npm run build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "upload"                                   # <-- REQUIRED
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_RED_GLACIER_0936E2203 }}
          app_location: "/"                                  # folder with package.json
          api_location: ""                                   # no API
          output_location: "build"                           # CRA output
          skip_app_build: true                               # we already built

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_RED_GLACIER_0936E2203 }}